spring:

  thymeleaf:
    #thymeleaf 模板配置
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 禁用缓存
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  # 数据库
  datasource:
    # 细节考虑下, p6spy 之后连接名都不一样了
    url: jdbc:p6spy:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 123456
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    #driverClassName: com.mysql.cj.jdbc.Driver
    # hikari连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5


  mail:
    #host: smtp.qq.com
    #username: 1627518680@qq.com
    #password: dzpgpicsydfoeedi
    host: smtp.163.com
    username: lcllge@163.com
    password: liang131456711



mybatis-plus:
  typeAliasesPackage: {com.lanzhou.yuanfen.*.entity}
  global-config:
    db-config:
      #逻辑删除策略
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #表前缀
      table-prefix: t_
  #mybatis-plus 枚举包
  typeEnumsPackage: com.lanzhou.yuanfen.enums


server:
  port: 8081


logging:
  level:
    root: info
